spring.config.import=optional:classpath:application-local.properties

spring.application.name=lecturboxd

spring.datasource.url=jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:6543/postgres?pgbouncer=true&prepareThreshold=0
spring.datasource.username=postgres.swxtcuvsgmbrylliiwoh
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.debug=true

jwt.expiration-ms=86400000

lecturboxd.allowed-email-domains=@freeuni.edu.ge,@agruni.edu.ge
lecturboxd.otp.expiration-minutes=10

lecturboxd.admin.api-key-header=X-Admin-Api-Key
